### ISSUE TITLE
将重点资源整理成一个生信导航网页

### ISSUE THREAD

**Issue by ShixiangWang** [ShixiangWang/self-study#65]

**Comment by ShixiangWang** [comment]
https://github.com/jtleek/reviews

**Comment by ShixiangWang** [comment]
- https://www.home-for-researchers.com/static/index.html#/
- hiplot

**Comment by ShixiangWang** [comment]
https://genomepaint.stjude.cloud

**Comment by shenweiyan** [comment]
这个提议好
![0075BED2](https://user-images.githubusercontent.com/26101369/167979638-6ae91423-c0d6-4352-9c36-374c7302adf1.png)

**Comment by DawnEve** [comment]
有模仿对象没？这个东西很多做技术的都需要

难点就是费老大劲做出来，结果发现不是自己想要的

**Comment by ShixiangWang** [comment]
@DawnEve 这个之前弄过，没时间整理这些，你感兴趣可以看看 https://github.com/BioSisyphus/guide

**Comment by DawnEve** [comment]
2022年， jsdelivr 的cdn 基本加载不上。打开就是最左侧一列

**Comment by shenweiyan** [comment]
> jsdelivr

 jsdelivr 貌似已经挂了

**Comment by shenweiyan** [comment]
参考诗翔老师的项目，准备自己折腾一下：https://github.com/bioitee/BioWebStack
